spring:
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 3612a98081b96d
    password: d7d0d3626676a3
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: L10-1-spring-security-DB
  datasource:
    url: jdbc:postgresql://localhost:5432/l10-1-spring-security-db
    username: us
    password: us
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        use_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

