version: '3'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: l10-1-spring-security-db
      POSTGRES_USER: us
      POSTGRES_PASSWORD: us
    ports:
      - "5432:5432"